// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft" | "lovable",
      opts?: SignInOptions,
    ) => {
      const host =
        typeof window !== "undefined" ? window.location.hostname : "";
      const onLovablePreview =
        host.endsWith(".lovable.app") ||
        host.endsWith(".lovableproject.com") ||
        host.endsWith(".lovableproject-dev.com");

      if (
        !onLovablePreview &&
        (provider === "google" ||
          provider === "apple" ||
          provider === "microsoft")
      ) {
        const supabaseProvider = provider === "microsoft" ? "azure" : provider;
        const { data, error } = await supabase.auth.signInWithOAuth({
          provider: supabaseProvider,
          options: {
            redirectTo:
              opts?.redirect_uri || `${window.location.origin}/prehlad`,
          },
        });
        if (error) return { error };
        return { redirected: true, data };
      }

      try {
        const result = await lovableAuth.signInWithOAuth(provider, {
          ...opts,
          extraParams: {
            ...opts?.extraParams,
          },
        });

        if (result.redirected) {
          return result;
        }

        if (result.error) {
          throw result.error instanceof Error
            ? result.error
            : new Error(String(result.error));
        }

        try {
          await supabase.auth.setSession(result.tokens);
        } catch (e) {
          return { error: e instanceof Error ? e : new Error(String(e)) };
        }
        return result;
      } catch (err) {
        if (
          provider === "google" ||
          provider === "apple" ||
          provider === "microsoft"
        ) {
          const supabaseProvider =
            provider === "microsoft" ? "azure" : provider;
          const { data, error } = await supabase.auth.signInWithOAuth({
            provider: supabaseProvider,
            options: {
              redirectTo:
                opts?.redirect_uri || `${window.location.origin}/prehlad`,
            },
          });
          if (error) return { error };
          return { redirected: true, data };
        }
        throw err;
      }
    },
  },
};
